README.md
wot-security-references.md

- put links in README pointing at other files
- copy over references as well

add references, links

---

index.html

Checking in content from old TD, lightly edited, and merged with basic HTML template.   content doesn't make sense in some places and is incomplete, so will go through a two-stage process (external pull request, merge from working to master) before becoming part of "official" content.

Initial checkin with content from old TD doc

---

README.md

Add contribution policy to README.   Please stage changes through the "working" branch.

sync new README.md

---

README.md

Update contribution policy.   Future commits should be staged through the "working" branch, please.

update README.md with working/master branch instructions

---

README.md

Add link in README to index.html.
Actually, we need to set up a "rendering" link as well to github.io...

link to index.html

---

index.html

Propose Elena as editor.   To be confirmed by another WG co-chair.  To confirm, accept pull request.

Add Elena Reshetova as Editor

---

index.html

Clean up abstract, converting it from point form to paragraphs.   Aimed at addressing Issue  https://github.com/w3c/wot-security/issues/17

Clean up abstract

---

index.html
tablestyle.css

PR to resolve issue https://github.com/w3c/wot-security/issues/16.
Adds CSS for better table formatting (funny these are not in ReSpec, maybe they should be upstreamed) and also changes to content in tables themselves (adding dfn links).

Fix table formatting for threat model

---

index.html

The rest left http links do not work on https.

Addressing various open issues

---

wot-security-metadata.md

To address some confusion, some simpler examples were added (examples now work up from simplest to most complex).

Simpler security metadata examples

---

index.html

Restructuring parts of the document + fixes

---

index.html

Release candidate... some cleanup still needed, though.

Merge Working into Master

---

index.html

Do not merge: just a mere start for the section
***
<a href="https://pr-preview.s3.amazonaws.com/ereshetova/wot-security/pull/150.html" title="Last updated on Nov 27, 2019, 9:40 AM UTC (caad0a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-security/150/c0280e3...ereshetova:caad0a8.html" title="Last updated on Nov 27, 2019, 9:40 AM UTC (caad0a8)">Diff</a>

an initial attempt on security provisioning section

---

Overview.html

Wording change (IETF ACE WG)

---

wot-security-best-practices.md

HTTPS => HTTPS-over-TLS etc (Issue#142)

HTTPS => HTTPS-over-TLS etc (Issue#142)

---

wot-security-metadata.md

HTTPS => HTTP-over-TLS etc. (Issue#142)

HTTPS => HTTP-over-TLS etc. (Issue#142)

---

index.html

Elaborated text on end-to-end security: 1 additional section plus 1 clarification for the existing section
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 9, 2020, 7:58 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fwot-security%2Febfcb5768c29f9813f2c0e5fa71316f5b3466aee%2Findex.html%3FisPreview%3Dtrue)
```
Navigation timeout of 30000 ms exceeded
```
_If you don't have enough …

Elaborated text on end-to-end security

---

index.html

Issue #144: text proposal for end-to-end security
***
<a href="https://pr-preview.s3.amazonaws.com/OliverPfaff/wot-security/pull/172.html" title="Last updated on May 15, 2020, 1:53 PM UTC (39d8e12)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-security/172/4166672...OliverPfaff:39d8e12.html" title="Last updated on May 15, 2020, 1:53 PM UTC (39d8e12)">Diff</a>

Issue #144: text proposal for end-to-end security

---

index.html

Added references and changed text (minor) for Issue #144
***
<a href="https://pr-preview.s3.amazonaws.com/OliverPfaff/wot-security/pull/176.html" title="Last updated on May 25, 2020, 7:50 AM UTC (3f938c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-security/176/d088c12...OliverPfaff:3f938c0.html" title="Last updated on May 25, 2020, 7:50 AM UTC (3f938c0)">Diff</a>

Changes for Issue #144: references/text

---

README.md

Working branch is causing confusion so will be deleting it. This PR just updates the README to remove the directions on how to use it.  Second attempt...

Prepare to delete Working branch - update README

---

background/hubs.md

add OpenHAB content from @OliverPfaff

Update hubs.md with OpenHABs content

---

index.html

This contains an initial attempt at expanding the introduction section. There is still some work to be done, but I think it could already be reviewed. I will try to finish it until the meeting on Monday.
~~I also had to remove the IMAGES file in this PR in order to be able to push the commit. Let me know if the file is too important to be deleted, then I will try to find a different solution for submitting this PR.~~
***
<a href="https://pr-preview.s3.amazonaws.com/JKRhb/wot-security/pull/217.html" title="Last updated on Mar 13, 2023, 12:34 PM UTC (f65b7c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-security/217/66d919a...JKRhb:f65b7c8.html" title="Last updated on Mar 13, 2023, 12:34 PM UTC (f65b7c8)">Diff</a>

Expand introduction section

---

README.md
index.html

Adds Distributed Denial of Service threat, and also mentions it in the three scenarios given.  Two versions, compromised device generating traffic (e.g. the Mirai scenario), and non-compromised device that acts as an amplifying network reflector.
***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-security/pull/225.html" title="Last updated on Sep 18, 2023, 1:16 PM UTC (91b8d3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-security/225/b5c0c4a...mmccool:91b8d3d.html" title="Last updated on Sep 18, 2023, 1:16 PM UTC (91b8d3d)">Diff</a>

Add DDoS Threats

---

index.html

resolves #213
***
<a href="https://pr-preview.s3.amazonaws.com/mahdanoura/wot-security/pull/232.html" title="Last updated on Oct 23, 2023, 1:11 PM UTC (a3e5dd3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-security/232/e6873e2...mahdanoura:a3e5dd3.html" title="Last updated on Oct 23, 2023, 1:11 PM UTC (a3e5dd3)">Diff</a>

changed requirement section to analysis
